DROP TABLE USERINFO;

CREATE TABLE USERINFO(
  USER_NO NUMBER NOT NULL,
  USER_ID VARCHAR2(50),
  USER_PAWD VARCHAR2(150), --> 암호화 저장 
  USER_NAME VARCHAR2(50),
  USER_AGE NUMBER CHECK(USER_AGE >= 10 AND USER_AGE <= 100),
  USER_IMAGE VARCHAR2(100),
  USER_ADDRESS VARCHAR2(200) NOT NULL,
  USER_PHONENUMBER VARCHAR2(50),
  MAILPUSH_USE INTEGER, --> 1/0, 1 : push yes, 0 : push no
  ROLE VARCHAR2(20) NOT NULL, --security auth option
  PRIMARY KEY(USER_ID)
);

DESC USERINFO;


INSERT INTO USERINFO(
  USER_NO, USER_ID, USER_PAWD, USER_NAME, USER_AGE, USER_IMAGE, USER_ADDRESS, USER_PHONENUMBER, MAILPUSH_USE, ROLE) 
VALUES(
  1, 'scw3315', '1234', '서창욱', 26, 'sample1.png', '경기도 수원시', '01042084757', '1', 'ROLE_ADMIN');
  
INSERT INTO USERINFO(
  USER_NO, USER_ID, USER_PAWD, USER_NAME, USER_AGE, USER_IMAGE, USER_ADDRESS, USER_PHONENUMBER, MAILPUSH_USE, ROLE) 
VALUES(
  2, 'scw0531', '5678', '홍길동', 30, 'sample2.png', '서울특별시 강남구', '01011112222', '1', 'ROLE_ADMIN');
  
INSERT INTO USERINFO(
  USER_NO, USER_ID, USER_PAWD, USER_NAME, USER_AGE, USER_IMAGE, USER_ADDRESS, USER_PHONENUMBER, MAILPUSH_USE, ROLE) 
VALUES(
  3, 'scw1234', '1010', '임꺽정', 28, 'sample3.png', '경기도 안양시', '01033334444', '0', 'ROLE_USER');

COMMIT;

SELECT * FROM USERINFO;
