/* DDL : 데이터 정의어 */
/* Table Create */
DROP TABLE USERINFO;

-- 유저테이블 : 이름(PK) 나이 이미지
CREATE TABLE USERINFO(
  USER_NO NUMBER NOT NULL,
  USER_NAME VARCHAR2(100),
  USER_AGE NUMBER CHECK(USER_AGE >= 10 AND USER_AGE <= 100),
  USER_IMAGE VARCHAR2(100),
  USER_ROLE VARCHAR2(50) NOT NULL,
  PRIMARY KEY(USER_NAME)
)
;

/* DML : 데이터 조작어 */
/* DATA INSERT */
INSERT 
INTO    USERINFO(USER_NO, USER_NAME, USER_AGE, USER_IMAGE, USER_ROLE)
VALUES  (1, '서창욱', 26, 'sample1.png', 'ROLE_ADMIN')
;

INSERT 
INTO    USERINFO(USER_NO, USER_NAME, USER_AGE, USER_IMAGE, USER_ROLE)
VALUES  (2, '홍길동', 30, 'sample2.png', 'ROLE_ADMIN')
;

INSERT 
INTO    USERINFO(USER_NO, USER_NAME, USER_AGE, USER_IMAGE, USER_ROLE)
VALUES  (3, '임꺽정', 28, 'sample3.png', 'ROLE_USER')
;

/* DATA DELETE */
DELETE  
FROM  USERINFO
WHERE USERINFO.USER_NAME = '서창욱'
;

/* DATA SELECT */
SELECT  USER_NO, USER_NAME, USER_AGE, USER_IMAGE, USER_ROLE
FROM    USERINFO;

SELECT  USER_NO, USER_NAME, USER_AGE, USER_IMAGE, USER_ROLE
FROM    USERINFO
WHERE   USER_NAME = '서창욱';

/* TCL : 트랜잭션 제어어 */
/* 저장 */
COMMIT;

/* 취소 */
ROLLBACK;